More work on build scripts for nginx - now including OpenResty as optional setup, and examples of addon-build-scripts.

diff --git a/script/nginx-build/nginx-openresty b/script/nginx-build/nginx-openresty
--- a/script/nginx-build/nginx-openresty
+++ b/script/nginx-build/nginx-openresty
@@ -1,26 +1,51 @@
 #! /usr/bin/env sh
-
-VERSION='1.3.3'
-NAME="nginx-$VERSION"
 ROOT="$PWD"
+VENDOR="$ROOT/vendor"
 
-mkdir -p "$ROOT/vendor"
+NGINX_TITLE='Nginx/OpenResty'
+NGINX_NAME='ngx_openresty'
+NGINX_TAG='v1.2.1.7'
+NGINX_URL='git://github.com/agentzh/ngx_openresty.git'
+NGINX_PATH="$VENDOR/$NGINX_NAME-$NGINX_TAG"
 
-rm -rf "$ROOT/vendor/$NAME"
+# == INIT
 
-if [[ -f "$ROOT/vendor/$NAME.tar.gz" ]]; then
-  echo "[nginx-build]: EXISTS $NAME"
+# rm -rf "$NGINX_PATH"
+mkdir -p "$VENDOR"
+echo "[nginx-build]: CD $VENDOR"
+cd "$VENDOR"
+
+# == FETCH
+
+if [[ -s "$NGINX_PATH" ]]; then
+  echo "[nginx-build]: EXISTS $NGINX_PATH"
 else
-  echo "[nginx-build]: FETCH $NAME"
-  curl "http://nginx.org/download/$NAME.tar.gz" > "$ROOT/vendor/$NAME.tar.gz"
+  echo "[nginx-build]: CHECKOUT $NGINX_URL ($NGINX_TAG) > $NGINX_PATH"
+  ( git clone --branch "$NGINX_TAG" "$NGINX_URL" "$NGINX_PATH" && echo "[nginx-build]: OK" ) || ( echo "[nginx-build]: FAIL" && exit )
 fi
 
-tar xzvf "$ROOT/vendor/$NAME.tar.gz" -C "$ROOT/vendor"
+# == SETUP 1/2
 
-cd "$ROOT/vendor/$NAME"
+echo "[nginx-build]: CD $NGINX_PATH"
+cd "$NGINX_PATH"
 
-make clean -C "$ROOT/vendor/$NAME"
+echo "[nginx-build]: MAKE CLEAN"
+make clean
 
+echo "[nginx-build]: MAKE"
+( make -j4 && echo "[nginx-build]: OK" ) || (echo "[nginx-build]: FAIL" && exit)
+
+# == SETUP 2/2
+
+NGINX_VERSION=`echo "$NGINX_TAG" | tr -ds 'v' ''`
+
+echo "[nginx-build]: CD $NGINX_PATH/$NGINX_NAME-$NGINX_VERSION"
+cd "$NGINX_PATH/$NGINX_NAME-$NGINX_VERSION"
+
+echo "[nginx-build]: MAKE CLEAN"
+make clean
+
+echo "[nginx-build]: CONFIGURE"
 ./configure \
   --without-http_fastcgi_module \
   --without-http_ssi_module \
@@ -93,7 +118,7 @@ make clean -C "$ROOT/vendor/$NAME"
   #   ...
   #
 
+echo "[nginx-build]: MAKE"
+( make -j$(sysctl -n hw.ncpu) && echo "[nginx-build]: OK" ) || echo "[nginx-build]: FAIL"
 
-make -j4 && echo "[nginx-build]: OK"
-
-cd "$ROOT/vendor/$NAME"
+# == DONE
diff --git a/script/nginx-start b/script/nginx-start
--- a/script/nginx-start
+++ b/script/nginx-start
@@ -1,26 +1,45 @@
 #! /usr/bin/env sh
-
-VERSION='1.3.3'
-NAME="nginx-$VERSION"
 ROOT="$PWD"
+VENDOR="$PWD/vendor"
+TMP="$PWD/tmp"
+LOG="$PWD/logs"
 
-mkdir -p "$ROOT/logs"
-mkdir -p "$ROOT/tmp"
+if [[ $1 == 'openresty' ]]; then
+  NGINX_NAME='ngx_openresty'
+  NGINX_TAG='v1.2.1.7'
+  NGINX_PATH="$VENDOR/ngx_openresty-v1.2.1.7/ngx_openresty-1.2.1.7/build/nginx-1.2.1"
+  echo "openresty-local" > "$TMP/nginx.name"
+else
+  NGINX_NAME='nginx'
+  NGINX_TAG='stable-1.2'
+  NGINX_PATH="$VENDOR/nginx-stable-1.2"
+  echo "nginx-local" > "$TMP/nginx.name"
+fi
+
+mkdir -p "$LOG"
+mkdir -p "$TMP"
 
 echo "[nginx-start]: ROOT $ROOT"
 
-if [[ -d "$ROOT/vendor/$NAME/objs" ]]; then
-  echo "[nginx-start]: BIN $ROOT/vendor/$NAME/objs/nginx"
-  BIN="$ROOT/vendor/$NAME/objs/nginx"
+if [[ -d "$NGINX_PATH/objs" ]]; then
+  echo "[nginx-start]: BIN $NGINX_PATH/objs/nginx"
+  # nginx: local/sandboxed
+  BIN="$NGINX_PATH/objs/nginx"
 else
   echo "[nginx-start]: BIN nginx"
-  BIN="nginx"
+  # nginx: global/shared
+  BIN="nginx \
+        --uwsgi_temp_path $TMP/uwsgi_temp \
+        --fastcgi_temp_path $TMP/fastcgi_temp \
+        --scgi_temp_path $TMP/scgi_temp \
+        --proxy_temp_path $TMP/proxy_temp \
+        --client_body_temp_path $TMP/client_body_temp"
 fi
 
 echo "[nginx-start]: INFO Stopping Nginx in: $ROOT"
-([[ -s "$ROOT/tmp/nginx.pid" ]] && nginx -s quit -p `pwd`/ -c config/nginx.conf && echo "[nginx-start]: RESTART")
+( [[ -s "$TMP/nginx.pid" ]] && $BIN -s quit -p `pwd`/ -c config/nginx.conf && echo "[nginx-start]: RESTART" )
 
 echo "[nginx-start]: INFO Starting Nginx in: $ROOT"
-$BIN -p `pwd`/ -c config/nginx.conf && echo '[nginx-start]: OK'
+( $BIN -p `pwd`/ -c config/nginx.conf && echo '[nginx-start]: OK' ) || echo "[nginx-start]: FAIL"
 
-echo "[nginx-start]: PID $(cat "$ROOT/tmp/nginx.pid")"
+echo "[nginx-start]: PID $(cat "$TMP/nginx.pid")"
