Playing around with Foreman a bit.

diff --git a/script/nginx-start b/script/nginx-start
--- a/script/nginx-start
+++ b/script/nginx-start
@@ -1,32 +1,37 @@
 #! /usr/bin/env sh
 ROOT="$PWD"
+CONFIG="$PWD/config"
 VENDOR="$PWD/vendor"
 TMP="$PWD/tmp"
 LOG="$PWD/logs"
+
+PID_FILE="$TMP/nginx.pid"
+SID_FILE="$TMP/nginx.sid"
+DEFAULT_CONFIG_PATH="$PWD/config"
+CONFIG_PATH="$TMP/config"
+CONFIG_FILE="$CONFIG_PATH/nginx.conf"
 
 if [[ $1 == 'openresty' ]]; then
   NGINX_NAME='ngx_openresty'
   NGINX_TAG='v1.2.1.7'
   NGINX_PATH="$VENDOR/ngx_openresty-v1.2.1.7/ngx_openresty-1.2.1.7/build/nginx-1.2.1"
-  echo "openresty-local" > "$TMP/nginx.name"
+  echo "openresty-local" > $SID_FILE
 else
   NGINX_NAME='nginx'
   NGINX_TAG='stable-1.2'
   NGINX_PATH="$VENDOR/nginx-stable-1.2"
-  echo "nginx-local" > "$TMP/nginx.name"
+  echo "nginx-local" > $SID_FILE
 fi
 
-mkdir -p "$LOG"
-mkdir -p "$TMP"
+mkdir -p $LOG
+mkdir -p $TMP
 
 echo "[nginx-start]: ROOT $ROOT"
 
 if [[ -d "$NGINX_PATH/objs" ]]; then
-  echo "[nginx-start]: BIN $NGINX_PATH/objs/nginx"
   # nginx: local/sandboxed
   BIN="$NGINX_PATH/objs/nginx"
 else
-  echo "[nginx-start]: BIN nginx"
   # nginx: global/shared
   BIN="nginx \
         --uwsgi_temp_path $TMP/uwsgi_temp \
@@ -36,10 +41,32 @@ else
         --client_body_temp_path $TMP/client_body_temp"
 fi
 
-echo "[nginx-start]: INFO Stopping Nginx in: $ROOT"
-( [[ -s "$TMP/nginx.pid" ]] && $BIN -s quit -p `pwd`/ -c config/nginx.conf && echo "[nginx-start]: RESTART" )
+echo "[nginx-start]: BIN $BIN"
+
+echo "[nginx-stop]: GENERATE $DEFAULT_CONFIG_PATH > $CONFIG_PATH"
+rm -rf $CONFIG_PATH
+cp -r $DEFAULT_CONFIG_PATH $CONFIG_PATH
+
+if [ -z $PORT ]; then
+  echo "[nginx-start]: PORT -"
+else
+  echo "[nginx-start]: PORT $PORT"
+  sed -i '' -e 's/daemon on/daemon off/g' "$CONFIG_PATH/nginx.conf"
+  sed -i '' -e "s/listen [0-9]+ default;/listen $(echo $PORT || echo '8080') default;/g" $CONFIG_PATH/sites/default.conf
+fi
+
+if [[ -s $PID_FILE ]]; then
+  echo "[nginx-start]: INFO Stopping Nginx in: $ROOT"
+  ( $BIN -s quit -p `pwd`/ -c $CONFIG_FILE ) && echo "[nginx-start]: RESTART"
+fi
 
 echo "[nginx-start]: INFO Starting Nginx in: $ROOT"
-( $BIN -p `pwd`/ -c config/nginx.conf && echo '[nginx-start]: OK' ) || echo "[nginx-start]: FAIL"
+( $BIN -p `pwd`/ -c $CONFIG_FILE && echo '[nginx-start]: OK' ) || echo "[nginx-start]: FAIL"
 
-echo "[nginx-start]: PID $(cat "$TMP/nginx.pid")"
+# NOTE: If Nginx config 'daemon off;' is set no PID is written out becuase of the blocking call - not sure how to do that in a simple way.
+
+if [[ -f $PID_FILE ]]; then
+  echo "[nginx-start]: PID $(cat $PID_FILE)"
+else
+  echo "[nginx-start]: PID -"
+fi
